sudo: false
language: node_js
node_js:
  - 14.17.6
cache: npm
branches:
  only:
    - main
script:
  - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - cnpm install -g hexo
  - cnpm install -g hexo-cli
  - npm install
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
  