sudo: false
language: node_js
dist: focal
node_js:
  - 14.17.6
cache: npm
branches:
  only:
    - main
install:
  - npm install -g npm@7.24.0
  #- npm install -g cnpm --registry=https://registry.npm.taobao.org
  - npm install hexo-cli -g
  - npm install hexo -g
  - npm install
  #- npm audit fix --force
script:
  - rm -f ./source/_posts/hello-world.md
  - npm ls --depth 0
  - hexo g
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public