# 主题颜色
color:
  primary: indigo
  accent: pink

header_picture_link: https://cdn.jsdelivr.net/gh/Yuameshi/Blog-CDN@main/background-pictures/87489781_p0.webp
avatar: https://cdn.jsdelivr.net/gh/Yuameshi/Blog-CDN@main/background-pictures/Avatar.png
favicon: https://cdn.jsdelivr.net/gh/Yuameshi/Blog-CDN@main/background-pictures/Avatar.png
excerpt_length: 250 #自动生成的摘要长度 建议文章中手动使用 <!--more--> 效果更佳  
tag_page_count: true #Tag页是否计数

# 搜索
search:
  local: true
  path: /search.xml

# 文章末尾插入的文段，%title%表示文章标题，%link%表示文章链接
passage_end_tag:
  enabled: true
  text: '本文链接：<a href="%link%">%link%</a><br> 本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/deed" target="_blank" rel="noopener">CC BY-NC-SA 3.0</a> 协议进行许可'

# 抽屉菜单
# 格式: 名称: 链接 || 前缀(图标)
# 图标到找 https://www.mdui.org/docs/material_icon
drawer:
  主页: / || &#xe88a;
  睿站主页: https://b23.tv/CRByKN || &#xe04b;
  基友们: /friends || &#xe7fb;
  Gay♂Hub: https://github.com/Yuameshi || &#xe869;
  PhiCommunity: https://phicommunity.com.cn || &#xe149;
  归档: /archives || &#xe149;
  关于: /about || &#xe88e;
  憨憨の服务状态: https://status.yuameshi.top/ || &#xe24b;

drawer_about:
  enable: true
  name: Yuameshi
  slogan: qwq
  background: https://cdn.jsdelivr.net/gh/Yuameshi/Blog-CDN@main/background-pictures/87478484_p0.webp
  is_dark: true

friend_links:
  DrBlackの锦里: https://www.drblack-system.com/
  榆 木 脑 袋: https://drbstore.han-han.xyz/
  Colstone: https://colstone.xyz/
  ShiSheng's Blog: https://blog.shisheng.icu/
  Hicool嗨酷: https://www.hicool.icu/
  xkww3n's site: https://www.xkww3n.cyou/
  Dr-MengBao: https://www.drmengbao.site/
  SkipM4的日记本: https://skipm4.com/
  Made by qwe: https://www.10086.fund/

footer:
  since: 2019
  copyrights: true
  hexo: true
  theme: true
  text: Hello World!
  contact:
    Github: https://github.com/Yuameshi/ || fa fa-github
    Email: mailto:yuameshi@outlook.com || fa fa-envelope
    Steam: https://steamcommunity.com/id/2636099143 || fa fa-steam
    Twitter: https://twitter.com/HanHan_233 || fa fa-twitter
    TelegramAccount: https://t.me/yuameshi || fa fa-telegram
    TelegramChannel: https://t.me/Yuameshi_Words || fa fa-telegram
  miit_icp: 
  moe_icp: 20224680