# Theme config
router: true

style:
  primary_color: "indigo"
  accent_color: "pink"
  bg_color: "#eeeeee"
  hoverable: true

info:
  bg_image: https://cdn.han-han.xyz/background-pictures/87478484_p0.jpg
  avatar: https://cdn.han-han.xyz/background-pictures/Avatar.png
  slogan: "public const 憨憨=\"大废物\""
  sns:
    QQ: 
      link: '/about/#%E8%81%94%E7%B3%BB%E6%88%91'
      fa: 'fa-qq'
    Twitter:
      link: https://twitter.com/HanHan_233
      fa: 'fa-twitter'
    GitHub:
      link: https://github.com/Yuameshi
      fa: 'fa-github'
    Telegram:
      link: https://t.me/yuameshi
      fa: 'fa-telegram'
    Steam:
      link: https://steamcommunity.com/id/2636099143
      fa: 'fa-steam'
    #BiliBili:
      #link: https://b23.tv/7bJOta
      #fa: 'fa-bilibili'
    Mail:
      link: 'mailto:hanhan.233@qq.com'
      md: '&#xe158;'

# HTML head
head:
  favicon: https://cdn.han-han.xyz/background-pictures/Avatar.png
  high_res_favicon: https://cdn.han-han.xyz/background-pictures/Avatar.png
  apple_touch_icon: https://cdn.han-han.xyz/background-pictures/Avatar.png
  keywords: blog, hexo, mdui

# Search
search: true

# Post
post:
  entry_excerpt: 80
  random_pics: 44
  qr_code: false
  prism:
    theme: darcula
    line_number: true
  license:
    name: 'CC BY-NC-SA 4.0'
    link:  'https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh'
  word_count: true
  read_time: true
  donate:
    爱发电:
      link: 'https://cdn.han-han.xyz/background-pictures/afdian-憨憨.jpg'
      fa: 'fa-afadian'
    微信:
      link: 'https://cdn.jsdelivr.net/gh/Yuameshi/Blog-CDN@main/background-pictures/wechatRewardCode.png'
      fa: 'fa-wechat'
    QQ:
      link: 'https://cdn.jsdelivr.net/gh/Yuameshi/Blog-CDN@main/background-pictures/qqPaymentCode.png'
      fa: 'fa-qq'

share_menu:
  rss: true
  weibo: true
  twitter: true
  facebook: true
  googleplus: true
  linkedin: true
  qq: true
  telegram: true

pages:
  睿站主页:
    link: "https://b23.tv/CRByKN"
    type: 'external'
    md: "&#xe04b;"
  基友们:
    link: "/friends"
    type: 'internal'
    md: "&#xe7fb;"
  Gay♂Hub:
    link: "https://github.com/Yuameshi"
    type: 'external'
    md: "&#xe869;"
  关于&联系我:
    link: "/about"
    type: 'internal'
    md: "&#xe853;"

# comment
comment:
    use:
    shortname:

# footer
footer:
  since: 2020
  ICP:
  image:
  last_updated:

# Service Worker
service_worker:

# scss
node_sass:
  debug: false
  outputStyle: compressed
  precision: 5
  sourceComments: false

# Vendors
vendors:
  style_min_css:
  outdatedbrowser_min_js:
  js_min_js:
  custom_head:
  custom_js:

debug: false