# 主题设置
use_cdn: true # 是否使用 CDN 加速（cdn.jsdelivr.net）

# 主题颜色
color:
  primary: indigo
  accent: pink

gdpr_cookie_alert:
  enable: true
  text: 此网站使用Cookie来改善您的体验。<br><a aria-label="view our privacy policy" class="mdui-text-color-theme-accent" href="/privacy/" target="_blank">点此查看我们的隐私政策</a><br><a aria-label="learn more about cookies" class="mdui-text-color-theme-accent" href="https://www.cookiesandyou.com" rel="noopener noreferrer nofollow" target="_blank">什么是Cookies</a>

header_picture_link: https://cdn.jsdelivr.net/gh/Yuameshi/Blog-CDN@main/background-pictures/87489781_p0.3840px.webp
favicon: /favicon.ico
excerpt_length: 250 #自动生成的摘要长度 建议文章中手动使用 <!--more--> 效果更佳  
tag_page_count: true #Tag页是否计数

# 搜索(还没做)
search:
  local: true
  path: /search.xml

# 抽屉菜单的关于
drawer_about:
  enable: true
  avatar: https://cdn.jsdelivr.net/gh/Yuameshi/Blog-CDN@main/background-pictures/Avatar.150px.webp
  name: Yuameshi
  slogan: qwq
  background: https://cdn.jsdelivr.net/gh/Yuameshi/Blog-CDN@main/background-pictures/87478484_p0.1000px.webp
  is_dark: true

# 抽屉菜单
# 格式: 名称: 链接 || 前缀(图标)
# 图标到找 https://www.mdui.org/docs/material_icon
drawer:
  主页: / || &#xe88a;
  睿站主页: https://b23.tv/CRByKN || &#xe04b;
  基友们: /friends || &#xe7fb;
  Gay♂Hub: https://github.com/Yuameshi || &#xe869;
  PhiCommunity: https://phicommunity.com.cn || &#xe149;
  关于: /about || &#xe88e;
  Yuameshiの服务状态: https://status.yuameshi.top/ || &#xe24b;

# 文章末尾插入的文段，%title%表示文章标题，%link%表示文章链接
passage_end_tag:
  enabled: true
  text: '本文链接：<a href="%link%">%link%</a><br>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/deed" target="_blank" rel="noopener">CC BY-NC-SA 3.0</a> 协议进行许可'

comment:
  use: 'utterances'
  gitalk:
    clientID: 
    clientSecret: 
    repo: 
    owner: 
    admin: ['']
    distractionFreeMode: true
  utterances:
    repo: Yuameshi/MyBlog
    issue_term: pathname
    lable: utteranc
    theme: preferred-color-scheme


analytics:
  google:
    enabled: false
    tracking_id: 
  cloudflare:
    enabled: false
    token: 

footer:
  since: 2019
  copyrights: true
  hexo: true
  theme: true
  text: 
  contact:
    Github: https://github.com/Yuameshi/
    Email: mailto:yuameshi@outlook.com
    Twitter: https://twitter.com/Yuameshi
    Telegram: https://t.me/yuameshi
    TGChannel: https://t.me/Yuameshi_Words
  miit_icp: 
  moe_icp: 20224680